actors:
  miyamoto:
    image_url: /images/actors/miyamoto.jpg
    name: yahsan2
    url: https://twitter.com/yahsan2
  sugi:
    image_url: /images/actors/sugi.jpg
    name: koheiSG
    url: https://twitter.com/koheiSG
  terada:
    image_url: /images/actors/terada.jpg
    name: naokazu_terada
    url: https://twitter.com/naokazu_terada
author: alice
description: ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£â€DevelopersJPâ€å‘¨è¾ºã«ãŸã‚€ã‚ã™ã‚‹ãƒãƒ©çŒ«ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãŸã¡ãŒã€è¿‘é ƒæµè¡Œã‚Šã®ãƒ†ãƒƒã‚¯ç³»ãƒãƒƒãƒ‰ã‚­ãƒ£ã‚¹ãƒˆã‚’â€œã‚µã‚«ãƒŠâ€œ ğŸŸ ã«è©±ã™ç•ªçµ„ã§ã™ã€‚
description_long: ã‚ªãƒ³ãƒ©ã‚¤ãƒ³ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£â€DevelopersJPâ€å‘¨è¾ºã«ãŸã‚€ã‚ã™ã‚‹ãƒãƒ©çŒ«ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãŸã¡ãŒã€è¿‘é ƒæµè¡Œã‚Šã®ãƒ†ãƒƒã‚¯ç³»ãƒãƒƒãƒ‰ã‚­ãƒ£ã‚¹ãƒˆã‚’â€œã‚µã‚«ãƒŠâ€œ ğŸŸ ã«è©±ã™ç•ªçµ„ã§ã™ã€‚DevelopersJPã¯ã€ãƒ•ãƒªãƒ¼ãƒ©ãƒ³ã‚¹ã‚„å°ã•ãªä¼šç¤¾ã®ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãŒé›†ã£ã¦ã€ã‚ã„ã‚ã„ãƒ¯ã‚¤ãƒ¯ã‚¤ã—ã¦ã‚‹Slack ã®ã“ã¨ã§ã™ã€‚
email: noracast.podcast@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: noracast
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: noracast
url: https://noracast.netlify.com
